version: '3'
services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /usr/app/go.mod go.sum
      - .:/usr/app
  go-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/go.mod go.sum
      - .:/usr/app
    command:
      [
        "go",
        "test",
        "-v",
      ]
#  "./...",
#         "-coverprofile",
#         "cover.out"